### ISSUE TITLE
CUDA_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by adaxidedakaonang** [dfki-av/AWT-for-CISS#1]
Hi, thanks for your code. I can successfully run the initial step. But for the following steps, I got the cuda out of memory error (even if I set batch size to 1). I use the offered script: 15-1, and the error is :
```
Old Model weights loaded for computing attributions
bkg cls  torch.Size([256, 1, 1])
Traceback (most recent call last):
  File "attribute.py", line 336, in <module>
    main(opts)
  File "attribute.py", line 255, in main
    attribution = lig.attribute(images, target=0, n_steps=n_step, attribute_to_layer_input=True)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/captum/log/__init__.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/captum/attr/_core/layer/layer_integrated_gradients.py", line 503, in attribute
    return_convergence_delta=False,
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py", line 292, in attribute
    method=method,
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py", line 355, in _attribute
    additional_forward_args=input_additional_args,
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/captum/attr/_core/layer/layer_integrated_gradients.py", line 471, in gradient_func
    self.forward_func, tuple(), target_ind, additional_forward_args
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/captum/_utils/common.py", line 485, in _run_forward
    else inputs
  File "attribute.py", line 216, in prev
    out = model_old(inp)[0]
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/lttm/Desktop/chang/AWT-for-CISS/segmentation_module.py", line 315, in forward
    out = self._network(x, ret_intermediate, only_bg=only_bg)
  File "/home/lttm/Desktop/chang/AWT-for-CISS/segmentation_module.py", line 162, in _network
    x_b, attentions = self.body(x)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/Desktop/chang/AWT-for-CISS/models/resnet.py", line 134, in forward
    x, att = self.mod4(x)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/Desktop/chang/AWT-for-CISS/modules/residual.py", line 125, in forward
    x = self.convs(x) + residual
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 23.68 GiB total capacity; 20.49 GiB already allocated; 222.94 MiB free; 21.08 GiB reserved in total by PyTorch)
Killing subprocess 2825883
Traceback (most recent call last):
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/lttm/miniconda3/envs/pytorch1.8/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lttm/miniconda3/envs/pytorch1.8/bin/python3', '-u', 'attribute.py', '--local_rank=0', '--date', '2023-07-26', '--data_root', '/home/lttm/Desktop/chang/EWF_official/PascalVOC12/', '--overlap', '--batch_size', '1', '--dataset', 'voc', '--name', 'MiB', '--task', '15-1', '--step', '1', '--lr', '0.0003', '--method', 'MiB', '--opt_level', 'O2', '--checkpoint', 'checkpoints/step/lr_0.02/', '--att', '25', '--mask_att']' returned non-zero exit status 1.
```
Or if it's convenience, can you please offer the tested pascal images of setting 15-1? Thank you very much :)

**Comment by dipamgoswami** [comment]
Hi @adaxidedakaonang, sorry for the late response.

It looks like the attribution computation process will require more cuda memory. You can try using 2 GPUs if you have access to them (I performed the experiments using 2 A100 or 2 RTX6000 GPUs, both worked perfectly fine with me). 

I have some tested images from PASCAL VOC in 10-1 setting, provided in the supplementary materials of the WACV 23 paper. Let me know if that is sufficient for you. Otherwise, I can try to share the 15-1 setting inference images in some time.

**Comment by adaxidedakaonang** [comment]
Thank you very much! For now, the 10-1 images are enough for me.
